org: superkruger
app: decentravest
service: events

provider:
  name: aws
  region: us-east-1
  memorySize: 256
  runtime: nodejs12.x
  role: LambdaRole
  timeout: 120
  environment:
    STAGE: ${opt:stage, 'dev'}
    #mysql
    MYSQL_HOST: ${self:custom.MYSQL.HOST}
    MYSQL_PORT: ${self:custom.MYSQL.PORT}
    DB_NAME: decentravest
    USERNAME: master
    PASSWORD: password
    #s3
    tradingbucket: ${self:custom.tradingbucket}
    eventbucket: ${self:custom.eventbucket}
    eventbucket_queryresults: ${self:custom.eventbucket_queryresults}
    traderstatisticsbucket: ${self:custom.traderstatisticsbucket}
    investorstatisticsbucket: ${self:custom.investorstatisticsbucket}
    investmentbucket: ${self:custom.investmentbucket}
    #infura
    INFURA_BASE_URL: ${param:INFURA_BASE_URL}
    INFURA_API_KEY: ${param:INFURA_API_KEY}
    #dydx
    DYDX_CLOSED_MARKET_URL: ${param:DYDX_CLOSED_MARKET_URL}
    #tokens
    DAI_ADDRESS: ${param:DAI_ADDRESS}
    USDC_ADDRESS: ${param:USDC_ADDRESS}
    SAI_ADDRESS: ${param:SAI_ADDRESS}
custom:
  DB_NAME: decentravest
  USERNAME: master
  PASSWORD: password
  MYSQL:
    HOST:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Address]
    PORT:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Port]

  tradingbucket: "tradingbucket-${opt:stage, 'dev'}-1"
  eventbucket: "eventbucket-${opt:stage, 'dev'}-1"
  eventbucket_queryresults: "resultbucket-${opt:stage, 'dev'}-1"
  traderstatisticsbucket: "traderstatisticsbucket-${opt:stage, 'dev'}-1"
  investorstatisticsbucket: "investorstatisticsbucket-${opt:stage, 'dev'}-1"
  investmentbucket: "investmentbucket-${opt:stage, 'dev'}-1"
  athenadb: "blockchain-events-${opt:stage, 'dev'}"
  VPC_CIDR: 10

plugins:
  - serverless-pseudo-parameters
resources:
  Resources:
    MySqlRDSInstance: ${file(./resource/mysql/MySqlRDSInstance.yml)}
    TradingBucket: ${file(./resource/S3BucketTrades.yml)}
    EventBucket: ${file(./resource/S3BucketEvents.yml)}
    AthenaBucket: ${file(./resource/S3BucketQueryResults.yml)}
    TraderStatisticsBucket: ${file(./resource/S3BucketTraderStatistics.yml)}
    InvestorStatisticsBucket: ${file(./resource/S3BucketInvestorStatistics.yml)}
    InvestmentBucket: ${file(./resource/S3BucketInvestments.yml)}
    LambdaRole: ${file(./resource/LambdaRole.yml)}
    ServerlessInternetGateway: ${file(./resource/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./resource/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./resource/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./resource/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./resource/ServerlessSubnetB.yml)}
    ServerlessSubnetC: ${file(./resource/ServerlessSubnetC.yml)}
    ServerlessSubnetGroup: ${file(./resource/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./resource/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./resource/RouteTablePublic.yml)}
    RoutePublic: ${file(./resource/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./resource/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./resource/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./resource/RouteTableAssociationSubnetC.yml)}

    AthenaDB: ${file(./resource/AthenaDB.yml)}
    AthenaTableTraderPairedAllocate: ${file(./resource/tables/traderpaired/Allocate.yml)}
    AthenaTableTraderPairedApproveExit: ${file(./resource/tables/traderpaired/ApproveExit.yml)}
    AthenaTableTraderPairedInvest: ${file(./resource/tables/traderpaired/Invest.yml)}
    AthenaTableTraderPairedInvestment: ${file(./resource/tables/traderpaired/Investment.yml)}
    AthenaTableTraderPairedInvestor: ${file(./resource/tables/traderpaired/Investor.yml)}
    AthenaTableTraderPairedProfitPercentages: ${file(./resource/tables/traderpaired/ProfitPercentages.yml)}
    AthenaTableTraderPairedRejectExit: ${file(./resource/tables/traderpaired/RejectExit.yml)}
    AthenaTableTraderPairedRequestExit: ${file(./resource/tables/traderpaired/RequestExit.yml)}
    AthenaTableTraderPairedStop: ${file(./resource/tables/traderpaired/Stop.yml)}
    AthenaTableTraderPairedTrader: ${file(./resource/tables/traderpaired/Trader.yml)}

    AthenaTableMultiSigFundWalletFactoryContractInstantiation: ${file(./resource/tables/multisigfundwalletfactory/ContractInstantiation.yml)}

    AthenaTableMultiSigFundWalletDisbursementCompleted: ${file(./resource/tables/multisigfundwallet/DisbursementCompleted.yml)}
    AthenaTableMultiSigFundWalletDisbursementCreated: ${file(./resource/tables/multisigfundwallet/DisbursementCreated.yml)}
    AthenaTableMultiSigFundWalletDisbursementRejected: ${file(./resource/tables/multisigfundwallet/DisbursementRejected.yml)}
    AthenaTableMultiSigFundWalletFund: ${file(./resource/tables/multisigfundwallet/Fund.yml)}
    AthenaTableMultiSigFundWalletPayout: ${file(./resource/tables/multisigfundwallet/Payout.yml)}
    AthenaTableMultiSigFundWalletSetTrader: ${file(./resource/tables/multisigfundwallet/SetTrader.yml)}
    AthenaTableMultiSigFundWalletStopped: ${file(./resource/tables/multisigfundwallet/Stopped.yml)}

    AthenaTableDydxPosition: ${file(./resource/tables/dydx/Position.yml)}

    AthenaTableInvestment: ${file(./resource/tables/Investment.yml)}

functions:
  processAllEvents:
    handler: handler.processAllEvents
    events:
      - schedule: rate(1 hour)

  processAllTrades:
    handler: handler.processAllTrades
    events:
      - schedule: rate(1 day)

  calculateAllTradersStatistics:
    handler: handler.calculateAllTradersStatistics
    events:
      - schedule: rate(1 day)

  calculateAllInvestorsStatistics:
    handler: handler.calculateAllInvestorsStatistics
    events:
      - schedule: rate(1 day)

  calculateAllInvestmentValues:
    handler: handler.calculateAllInvestmentValues
    events:
      - schedule: rate(1 day)

  getStatistics:
    handler: handler.statistics
    events:
      - http:
          path: statistics
          method: get
          cors: true

  getTrades:
    handler: handler.trades
    events:
      - http:
          path: trades
          method: get
          cors: true

  getInvestments:
    handler: handler.investments
    events:
      - http:
          path: investments
          method: get
          cors: true

  userAction:
    handler: handler.userAction
    events:
      - http:
          path: userAction
          method: post
          cors: true

